using System.ComponentModel;
using Spectre.Console;
using Spectre.Console.Cli;


// ReSharper disable AutoPropertyCanBeMadeGetOnly.Global
// ReSharper disable ClassNeverInstantiated.Global

namespace NoeticTools.Git2SemVer.Tool.CommandLine.Changelog;

public class ChangelogCommandSettings : CommonCommandSettings
{
    [CommandOption("-a|--artifact-url <URL>")]
    [Description("Optional url to a version's artifacts. May contain version placeholder '%VERSION%'.")]
    public string ArtifactLinkPattern { get; set; } = "";

    [CommandOption("--conv-commits-file-path <FILEPATH>", IsHidden = true)] // todo - hidden until implemented
    [DefaultValue("")]
    [Description("Path to conventional commits JSON file that was generated by Git2SemVer versioning. May be a relative or absolute path. If set, this file is use as input instead of running the versioning engine.")]
    // ReSharper disable once MemberCanBePrivate.Global
    public string ConvCommitsInfoFilePath { get; set; } = "";

    [CommandOption("-d|--data-directory <DIRECTORY>")]
    [DefaultValue(".git2semver/changelog")]
    [Description("Path to generator's data and configuration files directory. May be a relative or absolute path.")]
    public string DataDirectory { get; set; } = "";

    [CommandOption("--host-type <TYPE>")]
    [Description("Force the host type. Use for testing expected behaviour on other hosts. Valid values are 'Custom', 'Uncontrolled', 'TeamCity', or 'GitHub'.")]
    public string? HostType { get; set; } = null;

    [CommandOption("-o|--output <FILEPATH>")]
    [DefaultValue("CHANGELOG.md")]
    [Description("Generated changelog file path. May be a relative or absolute path. Set to empty string to disable file write.")]
    public string OutputFilePath { get; set; } = "";

    [CommandOption("-r|--release-as <TITLE>")]
    [DefaultValue("")]
    [Description("If not an empty string sets the changes version (normally version or 'Unreleased'). Does not need to version, any text permitted.")]
    public string ReleaseAs { get; set; } = "";

    [CommandOption("-v|--verbosity <LEVEL>")]
    [DefaultValue("info")]
    [Description("Sets output verbosity. Valid values are 'trace', 'debug', 'info', 'warning', or 'error'.")]
    public string Verbosity { get; set; } = "";

    [CommandOption("-s|--show")]
    [DefaultValue(false)]
    [Description("Show changelog in console.")]
    public bool WriteToConsole { get; set; }

    public override ValidationResult Validate()
    {
        if (ConvCommitsInfoFilePath.Length == 0)
        {
            return ValidationResult.Success();
        }

        return File.Exists(ConvCommitsInfoFilePath)
            ? ValidationResult.Success()
            : ValidationResult.Error("The conventional commits info file must exist");
    }
}