package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "PROJECT_EXT_11"
                displayName = "NoeticTools/Git2SemVer.MSBuild"
                repositoryURL = "https://github.com/NoeticTools/Git2SemVer"
                authType = storedToken {
                    tokenId = "tc_token_id:CID_3de2c2727993edab40e4371046ac9db7:-1:9e7b82f7-5941-476b-ba54-211a20bbb5ca"
                }
            }
        }
        feature1.apply {
        }
    }
}
